let sb,token;
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const money=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Math.round(n||0));
async function boot(){const cfg=await fetch('/api/public-config').then(r=>r.json());sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);const s=(await sb.auth.getSession()).data.session;if(s){token=s.access_token;await enter()}$('#loginBtn').onclick=login;$('#logout').onclick=async()=>{await sb.auth.signOut();location.reload()};document.querySelectorAll('#adminNav [data-section]').forEach(a=>a.onclick=()=>load(a.dataset.section));}
async function login(){const e=$('#email').value.trim();if(!e)return;const {error}=await sb.auth.signInWithOtp({email:e,options:{emailRedirectTo:location.origin+'/admin/'}});$('#loginMsg').innerHTML=error?`<p class="error">${esc(error.message)}</p>`:'<p class="success">Revisa tu correo para entrar.</p>'}
async function api(path,opts={}){opts.headers={...(opts.headers||{}),Authorization:`Bearer ${token}`};const r=await fetch(path,opts);const j=await r.json();if(!r.ok)throw Error(j.error||`HTTP ${r.status}`);return j}
async function enter(){try{await api('/api/admin/dashboard');$('#login').classList.add('hidden');$('#adminNav').classList.remove('hidden');$('#panel').classList.remove('hidden');load('dashboard')}catch(e){$('#loginMsg').innerHTML=`<p class="error">${esc(e.message)}. Verifica que tu usuario esté en admin_users y activo.</p>`}}
async function load(sec){try{if(sec==='dashboard')return dashboard();if(sec==='leads')return leads();if(sec==='customers')return simple('customers','Clientes');if(sec==='finance')return finance();if(sec==='payments')return payments();if(sec==='orders')return simple('orders','Órdenes');if(sec==='catalog')return catalog();if(sec==='tradein')return tradein();}catch(e){$('#panel').innerHTML=`<p class="error">${esc(e.message)}</p>`}}
async function dashboard(){const d=await api('/api/admin/dashboard');const k=d.data.kpis;$('#panel').innerHTML=`<div class="eyebrow">Resumen</div><h1>Operación KUOTA.</h1><div class="admin-grid"><div class="kpi"><span class="muted">Órdenes</span><strong>${k.orders_total}</strong></div><div class="kpi"><span class="muted">Pagadas</span><strong>${k.orders_paid}</strong></div><div class="kpi"><span class="muted">Contado recaudado</span><strong>${money(k.cash_paid)}</strong></div><div class="kpi"><span class="muted">Cartera pendiente</span><strong>${money(k.portfolio_pending)}</strong></div><div class="kpi"><span class="muted">Financiaciones activas</span><strong>${k.fin_active}</strong></div><div class="kpi"><span class="muted">Cuotas vencidas</span><strong>${k.overdue_installments}</strong></div><div class="kpi"><span class="muted">Recaudo hoy</span><strong>${money(k.day_collection)}</strong></div><div class="kpi"><span class="muted">Recaudo mes</span><strong>${money(k.month_collection)}</strong></div></div>`}
async function leads(){const d=await api('/api/admin/leads');const rows=d.data||[];$('#panel').innerHTML=`<div class="eyebrow">Solicitudes</div><h1>Leads.</h1><div class="table-wrap"><table class="table"><thead><tr><th>Tipo</th><th>Cliente</th><th>Equipo</th><th>Estado</th><th>Fecha</th><th>Acción</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.lead_type)}</td><td>${esc(x.customer_id||'—')}</td><td>${esc(x.device_label||'')}</td><td>${esc(x.status||'pending')}</td><td>${esc(x.created_at||'')}</td><td>${x.lead_type==='plan_b'&&x.status!=='approved'?`<button class="btn" data-approve="${esc(x.id)}">Aprobar inicial</button>`:''}</td></tr>`).join('')}</tbody></table></div>`;document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>approve(b.dataset.approve))}
async function approve(id){const method=prompt('Método de pago de inicial (efectivo, transferencia, etc.)');if(!method)return;const ref=prompt('Referencia de inicial (opcional)')||'';await api('/api/admin/finance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'approve_initial',leadId:id,initialPaymentMethod:method,initialReference:ref})});await leads()}
async function finance(){const d=await api('/api/admin/finance');const rows=d.data||[];$('#panel').innerHTML=`<div class="eyebrow">Cartera</div><h1>Financiaciones.</h1><div class="table-wrap"><table class="table"><thead><tr><th>Cliente</th><th>Equipo</th><th>Estado</th><th>Saldo</th><th>Inicial</th><th>Cuotas</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.customers?.full_name||x.customer_id)}</td><td>${esc(x.product_model||'')} ${esc(x.storage||'')}</td><td>${esc(x.status||'')}</td><td>${money(x.saldo_pendiente)}</td><td>${money(x.initial_amount)}</td><td>${esc(x.total_cuotas)}</td></tr>`).join('')}</tbody></table></div>`}
async function payments(){const d=await api('/api/admin/payments');const rows=d.data||[];$('#panel').innerHTML=`<div class="eyebrow">Recaudos</div><h1>Pagos.</h1><div class="notice">Los pagos manuales se registran de forma transaccional. Para registrar una cuota usa su ID y método.</div><div class="table-wrap"><table class="table"><thead><tr><th>Fecha</th><th>Financiación</th><th>Cuota</th><th>Monto</th><th>Método</th><th>Referencia</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.paid_at||x.created_at||'')}</td><td>${esc(x.financiacion_id)}</td><td>${esc(x.cuota_id||'Inicial')}</td><td>${money(x.monto)}</td><td>${esc(x.metodo)}</td><td>${esc(x.referencia||'')}</td></tr>`).join('')}</tbody></table></div>`}
async function simple(endpoint,title){const d=await api('/api/admin/'+endpoint);const rows=d.data||[];const keys=rows[0]?Object.keys(rows[0]).filter(k=>!['payload','image_urls'].includes(k)).slice(0,8):[];$('#panel').innerHTML=`<div class="eyebrow">${esc(title)}</div><h1>${esc(title)}.</h1><div class="table-wrap"><table class="table"><thead><tr>${keys.map(k=>`<th>${esc(k)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${keys.map(k=>`<td>${esc(typeof r[k]==='object'?JSON.stringify(r[k]):r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}

async function tradein(){const d=await api('/api/admin/trade-in-photos');const rows=d.data||[];$('#panel').innerHTML=`<div class="eyebrow">Plan C</div><h1>Retomas.</h1><div class="table-wrap"><table class="table"><thead><tr><th>Cliente</th><th>Equipo</th><th>Estado</th><th>Fotos</th><th>Fecha</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.customer_id||'—')}</td><td>${esc(x.device_label||'')}</td><td>${esc(x.status||'pending')}</td><td>${(x.image_urls||[]).length}</td><td>${esc(x.created_at||'')}</td><td>${(x.image_urls||[]).map(path=>`<button class="btn" data-photo="${esc(path)}">Ver foto</button>`).join(' ')}</td></tr>`).join('')}</tbody></table></div>`;document.querySelectorAll('[data-photo]').forEach(b=>b.onclick=async()=>{try{const r=await api('/api/admin/trade-in-photos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:b.dataset.photo})});window.open(r.url,'_blank','noopener')}catch(e){alert(e.message)}})}
async function catalog(){const d=await api('/api/admin/catalog');const rows=d.data||[];$('#panel').innerHTML=`<div class="eyebrow">Catálogo</div><h1>Productos.</h1><div class="actions"><button class="btn primary" id="newProduct">Nuevo producto</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Modelo</th><th>Categoría</th><th>Activo</th><th>Variantes</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.model)}</td><td>${esc(x.category)}</td><td>${x.active?'Sí':'No'}</td><td>${(x.variants||[]).length}</td><td><button class="btn" data-toggle="${esc(x.id)}" data-active="${!x.active}">${x.active?'Desactivar':'Activar'}</button></td></tr>`).join('')}</tbody></table></div>`;$('#newProduct').onclick=newProduct;document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>toggleProduct(b.dataset.toggle,b.dataset.active==='true'))}
async function toggleProduct(id,active){await api('/api/admin/catalog',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,active})});catalog()}
async function newProduct(){const model=prompt('Modelo');if(!model)return;const category=prompt('Categoría: nuevo o exhibicion','nuevo');if(!['nuevo','exhibicion'].includes(category))return alert('Categoría inválida');await api('/api/admin/catalog',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model,category,active:true,colors:[],family:'iPhone',sort_order:100})});catalog()}
boot();
